### ISSUE TITLE
Docker environment similar to Phpstan playground

### ISSUE THREAD

**Issue by dbalabka** [TysonAndre/phan-demo#1]
Hello @TysonAndre,

Did you consider the possibility to adjust https://github.com/phpstan/playground to run Phan? It sounds like just change static analysis tool instead of implementing a sandbox environment from scratch.

**Comment by TysonAndre** [comment]
This is a different approach entirely. I considered other demos such as phpstan's/psalm's.

- This runs entirely within the browser, and doesn't contact the server after webassembly loads (or at least it will once the bugs are fixed)
- https://github.com/phpstan/playground or the psalm playground require submitting the request to the server and running php on the server to finish the analysis (requires php hosting, persistent network connection, etc)

This might not even be the final version of a phan demo site
